### ISSUE TITLE
No output when run profiler

### ISSUE THREAD

**Issue by xplicit** [Microsoft/clr-samples#10]
I am trying to run profiler and see the output which it generates. Maybe I am wrong in understanding what it should do, but I expect to see "Enter" when entering the function execution and "Leave" when execution finished.

I created test project with `dotnet new && dotnet restore` and try to run the profiler with following command (on Linux):

```
CORECLR_PROFILER={cf0d821e-299b-5307-a3d8-b283c03916dd} CORECLR_ENABLE_PROFILING=1 CORECLR_PROFILER_PATH=/filePath/to/CorProfiler.so dotnet run
```
But in output I see only `Hello World!` and no one `Enter/Leave` What's wrong with this run? Documentation states that I should use `./corerun myassembly.dll` but I have no idea what is `./corerun` and suppose it's an old alias of `dotnet run`

**Comment by mjsabby** [comment]
corerun is the host when you build a coreclr repo.

Let me track down why CLI isn't working, I don't know yet.

**Comment by nickfloyd** [comment]
@xplicit try putting a log line in Initialize on `CorProfiler.cpp`

```
if (FAILED(queryInterfaceResult))
    {
        printf("\r\nFailed on query %" UINT_PTR_FORMAT "\r\n", queryInterfaceResult);
        return E_FAIL;
    }
```

You might find that the `queryInterfaceResult` is returning invalid. This would at least tell you if the profiler was trying to attach.

**Comment by mjsabby** [comment]
This was fixed a while back.
