### ISSUE TITLE
cocreateinstance failed

### ISSUE THREAD

**Issue by kenfullscale** [Microsoft/clr-samples#13]
profiler is not working in centos 7
Error: Loading profiler failed in cocreateinstance

**Comment by mjsabby** [comment]
@kenfullscale Does it work on any other linux distro you have access to? I'm able to to have this working on WSL Ubuntu 18.04 and regular Ubuntu 18.04.

**Comment by kenfullscale** [comment]
it works on ubuntu but it will fail in centOS or maybe RedHat base version.

**Comment by mjsabby** [comment]
Maybe your package is too old on centOS? If you want you could edit the sample to ask for a lower version like ICorProfilerInfo6 or 7

**Comment by kenfullscale** [comment]
I fix this issue by building corprofiler in centos distro. It seems that the build script is doing dynamic linking. Is it possible for static linking?

**Comment by mjsabby** [comment]
The profiler integration is a dynamic shared library. What piece are you making as a static lib?

**Comment by kgorro** [comment]
@mjsabby , this should be set to close.
