### ISSUE TITLE
Build bug: 'ICorProfilerCallback8': base class undefined

### ISSUE THREAD

**Issue by taliesins** [microsoft/clr-samples#14]
Build instructions should have this workaround added: https://github.com/Microsoft/BPerf/issues/13

**Comment by koepalex** [comment]
I get the errors like `undefined reference to 'IID_ICorProfilerInfo8'` while building **ReJITEnterLeaveHooks** example with ubuntu 20.04, could this be the same error?

Does someone have an idea how to solve it?
