### ISSUE TITLE
Dynamic Assembly loading

### ISSUE THREAD

**Issue by kgorro** [Microsoft/clr-samples#15]
Is it possible to dynamically load an assembly from the profiler? I tried to use libcoreclr.so and call some c# code that will perform assembly resolve but it fails to create another domain.

**Comment by kgorro** [comment]
@mjsabby maybe you have some idea.

**Comment by mjsabby** [comment]
You cannot directly load an assembly from the profiler by calling into the runtime.

However, you can modify IL, add metadata, etc to existing code such that an assembly is loaded. So for example you could add metadata to the first assembly that is loaded of your program and modify the method being JIt compiled to add code to do an assembly load, etc.

But if you provide more context maybe I can provide a better answer for what you want to achieve. For example I think there is a .Net Core feature called startup hooks or something where you can run some code at startup. I’m not sure of its status but maybe that is also an avenue.

**Comment by kgorro** [comment]
@mjsabby , so i can use AssemblyMetadata.CreateFromFile(String) Method?
And use the metadata being returned.
Startuphook is not supported in net framework.

**Comment by mjsabby** [comment]
I'm not aware of any other mechanism then. You'll need to do IL modification.

**Comment by kgorro** [comment]
@mjsabby , I am doing IL rewriting but my problem comes in when i tried to perform IL rewriting for an assembly that is not referenced by the project.

**Comment by mjsabby** [comment]
I'm not sure what you mean, how do you encounter this assembly that is not referenced by the project? If you encounter this assembly then by definition something must be accessing this assembly somehow.

**Comment by kgorro** [comment]
I am able to implement this one. This must be set to close

**Comment by Mahendra95-sys** [comment]
How can I dynamically load Managed assembly in to dotnet.exe from Native coreclr profiler?

**Comment by kgorro** [comment]
@Mahendra95-sys for .net core you need prepend a call to LoadFrom() at the entry point of each of the application.

**Comment by Mahendra95-sys** [comment]
@kgorro I am trying to Instrument .NET Core web applications that runs on .NET Core 3.1 using CoreCLR Profiler.
I have set the environment values CORECLR_PROFILER , CORECLR_ENABLE_PROFILING  and CORECLR_PROFILER_PATH, where my CoreCLRProfiler dll (CoreCLRProfiler.so)gets attached to dotnet.exe and it is getting the callbacks.

I am able to get all the callbacks,but when i allow injecting the code(ilrewrite) into the Webapplication's method then the app is getting crashed(dotnet.exe gets killed) as it couldnt find the injected function call.

I have created helper assembly(.NET standard 2.0) with the injected functions body and signed it with strong name and installed it in to the GAC. And also used DefineAssemblyRef(),DefineTypeRefByName() and DefineMemberRef() from IMetaDataAssemblyEmit to load assembly and its class methods. And also tried by placing dotnet standard dll in application folder. But the helper assembly is not loaded to dotnet.exe process.

Where should my helper assembly placed..? and

how can I load helper assembly to dotnet process from my native coreclr profiler?

**Comment by kgorro** [comment]
@Mahendra95-sys you need to get the entry point for every module being loaded and once the jitcompilation is triggered you need to identify if the functionToken is the entry point and once it is, inject a call (Assembly.LoadFrom()).

**Comment by Mahendra95-sys** [comment]
@kgorro Thank you for your answer.I am able to load helper assembly in to dotnet process,But it is Loading only after entry point.
Is there any way to load helper assembly in to dotnet process before entry point? Because I want to Inject methods those are called before entry point.

How can I load helper assembly from ModuleLoadFinished Instead of JitCompilationStarted ? Because I need to call DefineMemberRef() to define Injected methods for every module loaded Instead of every method is loaded.

**Comment by kgorro** [comment]
@Mahendra95-sys , this is just a theory, you can create a dynamic method that will be called in the entry point method to do the assembly loading.

**Comment by Mahendra95-sys** [comment]
@kgorro, Thanks for your information. Now I can able to load helper assembly successfully.
Can you help me to get Httpcontext of a .net core web request in helper assembly

**Comment by Durai-cpp** [comment]
@kgorro In my .NET profiler, We are using managed assembly C# which is installed in GAC to capture the injected function.
Now we wants to remove from GAC and have it into a directory. Can we have in c# dll into a directory ? How can we load this from c++ code .NET Profiler?

**Comment by kgorro** [comment]
@Durai-cpp yes it is possible and in fact, I am able to make it work, it needs a lot of IL rewriting and I cannot disclose the code for it since it is company property.
