### ISSUE TITLE
This sample does not work on Windows CoreCLR, failed at LoadLibrayExW call

### ISSUE THREAD

**Issue by test2020dev2020** [Microsoft/clr-samples#7]
I built CoreCLR and CoreFX, as well as this sample on 7/20/2016. It builds OK but failed on Windows 10 during LoadProfiler() process. 

Per instruction, I set following environment variables: 
set CORECLR_ENABLE_PROFILING=1
set CORECLR_PROFILER={cf0d821e-299b-5307-a3d8-b283c03916dd}
set CORECLR_PROFILER_PATH=D:\CoreCLR\GitHub\coreclr-demo\runtime\ClrProfiler.dll

and tried to run: CoreRun.exe hello.exe

It is failed in at line 65 at: https://github.com/dotnet/coreclr/blob/master/src/utilcode/longfilepathwrappers.cpp:

        if (LongFile::IsPathNotFullyQualified(path) || SUCCEEDED(LongFile::NormalizePath(path)))
        {
#ifndef FEATURE_PAL
            //Adding the assert to ensure relative paths which are not just filenames are not used for LoadLibrary Calls
            _ASSERTE(!LongFile::IsPathNotFullyQualified(path) || !LongFile::ContainsDirectorySeparator(path));
#endif //FEATURE_PAL

            ret = LoadLibraryExW(path.GetUnicode(), hFile, dwFlags);
        }
        
        lastError = GetLastError();

It failed on LoadLibraryExW() call.  right after the call, the last error number is 0xC1.

![image](https://cloud.githubusercontent.com/assets/20567581/17006832/aa0f24e4-4e98-11e6-8502-c77313518b67.png)

Error 0xC1 means: 

ERROR_BAD_EXE_FORMAT
193 (0xC1)
%1 is not a valid Win32 application.

according to: https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382(v=vs.85).aspx

Following is the callstack:

![image](https://cloud.githubusercontent.com/assets/20567581/17006716/b82b7588-4e97-11e6-8a0a-f6b8ce5a6c64.png)

**Comment by mjsabby** [comment]
I wasn't able to reproduce this @test2020dev2020. I tried a debug build, and looks like you may have too.

Maybe check the file path?

**Comment by kspawa** [comment]
@test2020dev2020 can you please confirm that you are using the right architecture for both the build of the profiler and the coreclr build. For example the instructions for the sample include building for a 64 bit architecture. Are you running it on a 64 bit coreclr as well?

**Comment by test2020dev2020** [comment]
I built it and test it on 64bit debug build on Windows 10 for both CoreCLR and the sample profiler. I tested the sample hello.cs from https://github.com/dotnet/coreclr/blob/master/Documentation/building/windows-instructions.md: 
using System;

public class Program
{
    public static void Main()
    {
        Console.WriteLine("Hello, Windows");
        Console.WriteLine("Love from CoreCLR.");
    }
}

I attached the screen shot for the build and test output from VS2015 developer command prompt.
![profiler](https://cloud.githubusercontent.com/assets/20567581/17042038/52489160-4f5f-11e6-89ae-92e4c2369028.png)

One minor thing is the instruction from: https://github.com/Microsoft/clr-samples/tree/master/ProfilingAPI/ReJITEnterLeaveHooks says Building on Windows, SET Output=CorProfiler.dll # default , however, after the build, I cannot find the CorProfiler.dll but ClrProfiler.dll so I assume we should use ClrProfiler.dll. 

I also tried to start a fresh new command line prompt:

![profiler2](https://cloud.githubusercontent.com/assets/20567581/17042156/360351d8-4f60-11e6-8278-14437da2279d.png)

I got the same thing, note even though it output says "Hello Widows
from CoreCLR build", it is not correct, I am expecting something like "function enter ******" prompt. If you load it under windbg, you will see it failed at LoadLibraryExW() with error code 0xC1. 

I will test it on another system to rule out if's not related with my system environment setting issues.

**Comment by test2020dev2020** [comment]
I reproduced the same failure in another Windows 10 system with 64bit debug build for both CoreCLR and the sample profiler. 

I will sync up with the latest CoreCLR and CoreFX to see if it still reproduce on Windows.

**Comment by kspawa** [comment]
@test2020dev2020 thank you for the detailed screen shots. Can you also share the command you use to build the profiler. Will it be possible to confirm that your ClrProfiler.dll is indeed 64 bits. If you run msbuild ClrProfiler.vcxproj then the default option is to build 32 bit instead of 64 bit. From a VS 2015 command prompt you can try dumpbin /headers clrprofiler.dll and check whether it says x86 or x64.

**Comment by test2020dev2020** [comment]
Thanks for the information. I was using VS 2015 command prompt instead of VS 2015 x64 native command prompt so that it builds 32bit profiler instead of 64bit profiler. Fix that and it can load correctly.  However, when run it with hello.exe, I see lots of enter ****/leave **** and then an error dialog pops up says "HEAP CORRUPTION DETECTED" . I am not sure this is expected. 

However, since it can load the library now, I am closing the issue. Thanks!

**Comment by kspawa** [comment]
@test2020dev2020 thanks for letting us know. I will update the readme to include this information so that any further confusion is reduced.

**Comment by mjsabby** [comment]
@test2020dev2020  tracking that issue as #8 - I ran into that as well, for now if you build retail you can continue forward.
